version: "3"
services:
  registration:
    image: andrey21and/bdc-registration-service
    network_mode: "host"
  settings:
    image: andrey21and/bdc-settings-service
    network_mode: "host"
  task:
    image: andrey21and/bdc-task-service
    depends_on:
      - registration
    network_mode: "host"
  runner:
    image: andrey21and/bdc-runner-service
    depends_on:
      - task
      - settings
    network_mode: "host"
  frontend:
    image: andrey21and/bdc-frontend
    depends_on:
      - runner
    network_mode: "host"